version: '3.8'

services:
  web:
    build: .
    command: flask run --host=0.0.0.0
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    depends_on:
      - redis
      - celery_worker

  redis:
    image: redis:6.0-alpine
    ports:
      - "6379:6379"

  celery_worker:
    build: .
    command: celery -A app.celery worker --loglevel=info
    depends_on:
      - redis
    volumes:
      - .:/app

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana

volumes:
  grafana-storage:
