version: '3.8'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - redis
      - solana-node
    command: ["gunicorn", "--bind", "0.0.0.0:5000", "--workers", "2", "main:app"]

  worker:
    build: .
    env_file:
      - .env
    command: ["celery", "-A", "tasks", "worker", "--loglevel=info"]
    depends_on:
      - redis
      - solana-node

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  solana-node:
    image: solanalabs/solana:v1.18.12
    ports:
      - "8899:8899"
      - "8900:8900"
    volumes:
      - solana_data:/root/.local/share/solana
    command: ["solana-validator", "--rpc-port", "8899", "--ledger", "/root/.local/share/solana"]

volumes:
  redis_data:
  solana_data:
